import type { Metadata, NextPage } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import AppProviders from '@/provider'
import poppins from '@/utils/font'

import './globals.css'

const RootLayout: NextPage<React.PropsWithChildren> = ({ children }) => (
  <html lang="en" suppressHydrationWarning>
    <body className={poppins.className}>
      <AppProviders>{children}</AppProviders>
    </body>
  </html>
)

export default RootLayout
