import type { Metadata, NextPage } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import poppins from '@/utils/font'
import './globals.css'
import { AuthProvider, MuiThemeProvider, NextThemeProvider } from '@/provider'

const RootLayout: NextPage<React.PropsWithChildren> = ({ children }) => (
  <html lang="en" suppressHydrationWarning>
    <body className={poppins.className}>
      <NextThemeProvider>
        <MuiThemeProvider>
          <AuthProvider>{children}</AuthProvider>
        </MuiThemeProvider>
      </NextThemeProvider>
    </body>
  </html>
)

export default RootLayout
