import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { cn } from '@/lib/utils'
import { GeistSans } from 'geist/font/sans'
import './globals.css'
import React from 'react'

const RootLayout: React.FC<React.PropsWithChildren> = ({ children }) => (
  <html lang="en">
    <body className={cn('min-h-screen bg-background font-sans antialiased', GeistSans.variable)}>
      {children}
    </body>
  </html>
)

export default RootLayout
